spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/costsheetgen_prod_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    hibernate:
      ddl-auto: validate # Never auto-create in production
    show-sql: false
    
server:
  port: ${PORT:8080}
  
cors:
  allowed-origins:
    - https://client.yourdomain.com
    - https://admin.yourdomain.com
    - https://rep.yourdomain.com
    
logging:
  level:
    org.hibernate.SQL: WARN
    com.yourcompany.yourapp: INFO